# what is the problem from this error produced and how can it be fixed?

names = ['bob', 'joe', 'susan', 'margaret']
# names['maragaret'] = 'jody'

names[3] = 'jody'


p names